let starttime = datetime(YYYY-MM-DD);
let endtime = now();
let DeviceInQuestion = "DEVICENAME";
union withsource=SourceTable 
    DeviceEvents,
    DeviceFileEvents,
    DeviceImageLoadEvents,
    DeviceLogonEvents,
    DeviceNetworkEvents,
    DeviceProcessEvents,
    DeviceRegistryEvents
//table exclusions
//| where $table != @"TableNameHere"
| where DeviceName contains DeviceInQuestion
| where Timestamp between (starttime .. endtime)
| sort by Timestamp desc
